# Copyright 2022 The Magma Authors.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: AGW Build & Format Python
on:
  push:
    branches:
      - master
      - 'v1.*'
    paths:
      - '**.py'
  pull_request_target:
    branches:
      - master
      - 'v1.*'
    paths:
      - '**.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  run-formatters-and-check-for-errors:
    name: Python Format Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3.1.0
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # pin@v2.11.1
        id: changes
        with:
          filters: |
            filesChanged:
              - added|modified: ["**/*.py"]
          list-files: 'shell'
      - name: Format and check for leftover changes
        id: check-run
        if: ${{ steps.changes.outputs.filesChanged == 'true' }}
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # pin@v3
        with:
          image: ghcr.io/magma/magma/python-precommit:latest
          options: -u 0 -v ${{ github.workspace }}:/code
          run: |
            echo "Running formatting tools. This should be equivalent to running './lte/gateway/python/precommit.py --format --diff' locally."
            for file in ${{ steps.changes.outputs.filesChanged_files }};
            do
              set -e
              echo ""
              echo "Running isort on $file...";
              isort --diff --check-only $file;
              echo "Running autopep8 on $file...";
              autopep8 --diff --exit-code --select W191,W291,W292,W293,W391,E131,E1,E2,E3 -r $file;
              echo "Running add-trailing-comma on $file...";
              add-trailing-comma --py35-plus $file;
            done;
      - uses: ./.github/workflows/composite/comment-on-pr
        if: always()
        env:
          check-type: Python format check
          check-documentation: See [instructions on running the formatter and linter locally](https://docs.magmacore.org/docs/next/lte/dev_unit_testing#format-agw).
        with:
          check-type: ${{ env.check-type }}
          check-documentation: ${{ env.check-documentation }}
          job-status: ${{ steps.check-run.outcome }}
